# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Check converter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout submodules
      run: |
        git submodule update --init --recursive
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check out custom models original files
      env:
        TOKEN: ${{ secrets.GitLabToken }}
      run: |
        rm -rf torch_models
        git clone https://github:"$TOKEN"@git.imxieyi.com/xieyi/waifu2x-custom-model-originals.git torch_models
    - name: Test model converters
      run: |
        python batch_convert.py
